In [2]:
import pandas as pd
import numpy as np

In [3]:
df_matches_goals = pd.read_csv("../data/processed/matches_goals_top50_last3seasons.csv")
df_delay_score = pd.read_csv("../data/processed/top50_players_delay_score.csv")

home/away difference

In [10]:
df_matches_goals["nb_home_goals"] = np.where((df_matches_goals["h_a"] == "h") & (df_matches_goals["goals"]>=1), 1, 0)
df_matches_goals["nb_away_goals"] = np.where((df_matches_goals["h_a"] == "a") & (df_matches_goals["goals"]>=1), 1, 0)

df = df_matches_goals.groupby(["player_id", "player"]).agg(
    total_home_goals=("nb_home_goals", "sum"),
    total_away_goals=("nb_away_goals", "sum")
).reset_index()

df["prop_home_goals"] = df["total_home_goals"] / (df["total_home_goals"] + df["total_away_goals"])
df["prop_away_goals"] = df["total_away_goals"] / (df["total_home_goals"] + df["total_away_goals"])

In [11]:
big_diff = df[(df["prop_home_goals"] > 0.65) | (df["prop_away_goals"] > 0.65)]
big_diff.sort_values(by="prop_home_goals", ascending=False)

,player_id,player,total_home_goals,total_away_goals,prop_home_goals,prop_away_goals
21,6531,Alexander Sørloth,40,16,0.714286,0.285714
9,3277,Alexandre Lacazette,24,10,0.705882,0.294118
29,8026,Raphinha,26,11,0.702703,0.297297
2,956,Andrej Kramaric,28,12,0.700000,0.300000
3,1235,Ante Budimir,38,17,0.690909,0.309091
14,5556,Ademola Lookman,22,10,0.687500,0.312500
15,5735,Jean-Philippe Mateta,28,13,0.682927,0.317073
40,9002,Vedat Muriqi,24,12,0.666667,0.333333

Delay score dataset

In [12]:
df_delay_score.head()

,player_id,player,avg_delay,median_delay,std_delay,min_delay,max_delay,big_drought_freq,actual_delay,delay_score,reliability_score
0,647,Harry Kane,77.773196,58.0,65.636389,2.0,325.0,0.134021,22,-0.849730,0.906860
1,3423,Kylian Mbappe-Lottin,90.753086,72.0,78.640246,2.0,419.0,0.111111,258,2.126734,0.872469
2,9749,Donyell Malen,128.971429,116.0,95.648402,9.0,460.0,0.057143,77,-0.543359,0.793678
3,7108,Jonathan Burkardt,120.631579,96.5,99.638379,4.0,450.0,0.078947,0,-1.210694,0.784677
4,3738,Serhou Guirassy,110.153846,71.0,121.216778,1.0,633.0,0.107692,25,-0.702492,0.741521

First, filter by player reliability, and then rank by delay score

In [14]:
data_delay = df_delay_score[df_delay_score["reliability_score"] > 0.6]
data_delay.sort_values("delay_score", ascending=False).reset_index(drop=True).head()

,player_id,player,avg_delay,median_delay,std_delay,min_delay,max_delay,big_drought_freq,actual_delay,delay_score,reliability_score
0,3423,Kylian Mbappe-Lottin,90.753086,72.0,78.640246,2.0,419.0,0.111111,258,2.126734,0.872469
1,3226,Ousmane Dembélé,101.750000,48.5,132.698056,5.0,589.0,0.156250,278,1.328203,0.686634
2,1235,Ante Budimir,146.000000,105.5,112.389485,9.0,446.0,0.092593,239,0.827480,0.669780
3,227,Robert Lewandowski,113.551724,93.0,108.818402,2.0,583.0,0.137931,197,0.766858,0.717436
4,1236,Patrik Schick,104.441860,61.0,118.844296,2.0,600.0,0.186047,182,0.652603,0.667830